import type { Product } from '@/product';

export const PRODUCTS_STUB: Product[] = [
  {
    id: 1,
    title: 'Essence Mascara Lash Princess',
    brand: 'Essence',
    category: 'beauty',
    price: 9.99,
    stock: 99,
  },
  {
    id: 2,
    title: 'Eyeshadow Palette with Mirror',
    brand: 'Glamour Beauty',
    category: 'beauty',
    price: 19.99,
    stock: 34,
  },
  {
    id: 3,
    title: 'Powder Canister',
    brand: 'Velvet Touch',
    category: 'beauty',
    price: 14.99,
    stock: 89,
  },
  {
    id: 4,
    title: 'Red Lipstick',
    brand: 'Chic Cosmetics',
    category: 'beauty',
    price: 12.99,
    stock: 91,
  },
  {
    id: 5,
    title: 'Red Nail Polish',
    brand: 'Nail Couture',
    category: 'beauty',
    price: 8.99,
    stock: 79,
  },
  {
    id: 6,
    title: 'Calvin Klein CK One',
    brand: 'Calvin Klein',
    category: 'fragrances',
    price: 49.99,
    stock: 29,
  },
  {
    id: 7,
    title: 'Chanel Coco Noir Eau De',
    brand: 'Chanel',
    category: 'fragrances',
    price: 129.99,
    stock: 58,
  },
  {
    id: 8,
    title: "Dior J'adore",
    brand: 'Dior',
    category: 'fragrances',
    price: 89.99,
    stock: 98,
  },
  {
    id: 9,
    title: 'Dolce Shine Eau de',
    brand: 'Dolce & Gabbana',
    category: 'fragrances',
    price: 69.99,
    stock: 4,
  },
  {
    id: 10,
    title: 'Gucci Bloom Eau de',
    brand: 'Gucci',
    category: 'fragrances',
    price: 79.99,
    stock: 91,
  },
  {
    id: 11,
    title: 'Annibale Colombo Bed',
    brand: 'Annibale Colombo',
    category: 'furniture',
    price: 1899.99,
    stock: 88,
  },
  {
    id: 12,
    title: 'Annibale Colombo Sofa',
    brand: 'Annibale Colombo',
    category: 'furniture',
    price: 2499.99,
    stock: 60,
  },
  {
    id: 13,
    title: 'Bedside Table African Cherry',
    brand: 'Furniture Co.',
    category: 'furniture',
    price: 299.99,
    stock: 64,
  },
  {
    id: 14,
    title: 'Knoll Saarinen Executive Conference Chair',
    brand: 'Knoll',
    category: 'furniture',
    price: 499.99,
    stock: 26,
  },
  {
    id: 15,
    title: 'Wooden Bathroom Sink With Mirror',
    brand: 'Bath Trends',
    category: 'furniture',
    price: 799.99,
    stock: 7,
  },
  {
    id: 16,
    title: 'Apple',
    category: 'groceries',
    price: 1.99,
    stock: 8,
  },
  {
    id: 17,
    title: 'Beef Steak',
    category: 'groceries',
    price: 12.99,
    stock: 86,
  },
  {
    id: 18,
    title: 'Cat Food',
    category: 'groceries',
    price: 8.99,
    stock: 46,
  },
  {
    id: 19,
    title: 'Chicken Meat',
    category: 'groceries',
    price: 9.99,
    stock: 97,
  },
  {
    id: 20,
    title: 'Cooking Oil',
    category: 'groceries',
    price: 4.99,
    stock: 10,
  },
  {
    id: 21,
    title: 'Cucumber',
    category: 'groceries',
    price: 1.49,
    stock: 84,
  },
  {
    id: 22,
    title: 'Dog Food',
    category: 'groceries',
    price: 10.99,
    stock: 71,
  },
  {
    id: 23,
    title: 'Eggs',
    category: 'groceries',
    price: 2.99,
    stock: 9,
  },
  {
    id: 24,
    title: 'Fish Steak',
    category: 'groceries',
    price: 14.99,
    stock: 74,
  },
  {
    id: 25,
    title: 'Green Bell Pepper',
    category: 'groceries',
    price: 1.29,
    stock: 33,
  },
  {
    id: 26,
    title: 'Green Chili Pepper',
    category: 'groceries',
    price: 0.99,
    stock: 3,
  },
  {
    id: 27,
    title: 'Honey Jar',
    category: 'groceries',
    price: 6.99,
    stock: 34,
  },
  {
    id: 28,
    title: 'Ice Cream',
    category: 'groceries',
    price: 5.49,
    stock: 27,
  },
  {
    id: 29,
    title: 'Juice',
    category: 'groceries',
    price: 3.99,
    stock: 50,
  },
  {
    id: 30,
    title: 'Kiwi',
    category: 'groceries',
    price: 2.49,
    stock: 99,
  },
  {
    id: 31,
    title: 'Lemon',
    category: 'groceries',
    price: 0.79,
    stock: 31,
  },
  {
    id: 32,
    title: 'Milk',
    category: 'groceries',
    price: 3.49,
    stock: 27,
  },
  {
    id: 33,
    title: 'Mulberry',
    category: 'groceries',
    price: 4.99,
    stock: 99,
  },
  {
    id: 34,
    title: 'Nescafe Coffee',
    category: 'groceries',
    price: 7.99,
    stock: 57,
  },
  {
    id: 35,
    title: 'Potatoes',
    category: 'groceries',
    price: 2.29,
    stock: 13,
  },
  {
    id: 36,
    title: 'Protein Powder',
    category: 'groceries',
    price: 19.99,
    stock: 80,
  },
  {
    id: 37,
    title: 'Red Onions',
    category: 'groceries',
    price: 1.99,
    stock: 82,
  },
  {
    id: 38,
    title: 'Rice',
    category: 'groceries',
    price: 5.99,
    stock: 59,
  },
  {
    id: 39,
    title: 'Soft Drinks',
    category: 'groceries',
    price: 1.99,
    stock: 53,
  },
  {
    id: 40,
    title: 'Strawberry',
    category: 'groceries',
    price: 3.99,
    stock: 46,
  },
  {
    id: 41,
    title: 'Tissue Paper Box',
    category: 'groceries',
    price: 2.49,
    stock: 86,
  },
  {
    id: 42,
    title: 'Water',
    category: 'groceries',
    price: 0.99,
    stock: 53,
  },
  {
    id: 43,
    title: 'Decoration Swing',
    category: 'home-decoration',
    price: 59.99,
    stock: 47,
  },
  {
    id: 44,
    title: 'Family Tree Photo Frame',
    category: 'home-decoration',
    price: 29.99,
    stock: 77,
  },
  {
    id: 45,
    title: 'House Showpiece Plant',
    category: 'home-decoration',
    price: 39.99,
    stock: 28,
  },
  {
    id: 46,
    title: 'Plant Pot',
    category: 'home-decoration',
    price: 14.99,
    stock: 59,
  },
  {
    id: 47,
    title: 'Table Lamp',
    category: 'home-decoration',
    price: 49.99,
    stock: 9,
  },
  {
    id: 48,
    title: 'Bamboo Spatula',
    category: 'kitchen-accessories',
    price: 7.99,
    stock: 37,
  },
  {
    id: 49,
    title: 'Black Aluminium Cup',
    category: 'kitchen-accessories',
    price: 5.99,
    stock: 75,
  },
  {
    id: 50,
    title: 'Black Whisk',
    category: 'kitchen-accessories',
    price: 9.99,
    stock: 73,
  },
  {
    id: 51,
    title: 'Boxed Blender',
    category: 'kitchen-accessories',
    price: 39.99,
    stock: 9,
  },
  {
    id: 52,
    title: 'Carbon Steel Wok',
    category: 'kitchen-accessories',
    price: 29.99,
    stock: 40,
  },
  {
    id: 53,
    title: 'Chopping Board',
    category: 'kitchen-accessories',
    price: 12.99,
    stock: 14,
  },
  {
    id: 54,
    title: 'Citrus Squeezer Yellow',
    category: 'kitchen-accessories',
    price: 8.99,
    stock: 22,
  },
  {
    id: 55,
    title: 'Egg Slicer',
    category: 'kitchen-accessories',
    price: 6.99,
    stock: 40,
  },
  {
    id: 56,
    title: 'Electric Stove',
    category: 'kitchen-accessories',
    price: 49.99,
    stock: 21,
  },
  {
    id: 57,
    title: 'Fine Mesh Strainer',
    category: 'kitchen-accessories',
    price: 9.99,
    stock: 85,
  },
  {
    id: 58,
    title: 'Fork',
    category: 'kitchen-accessories',
    price: 3.99,
    stock: 7,
  },
  {
    id: 59,
    title: 'Glass',
    category: 'kitchen-accessories',
    price: 4.99,
    stock: 46,
  },
  {
    id: 60,
    title: 'Grater Black',
    category: 'kitchen-accessories',
    price: 10.99,
    stock: 84,
  },
  {
    id: 61,
    title: 'Hand Blender',
    category: 'kitchen-accessories',
    price: 34.99,
    stock: 84,
  },
  {
    id: 62,
    title: 'Ice Cube Tray',
    category: 'kitchen-accessories',
    price: 5.99,
    stock: 13,
  },
  {
    id: 63,
    title: 'Kitchen Sieve',
    category: 'kitchen-accessories',
    price: 7.99,
    stock: 68,
  },
  {
    id: 64,
    title: 'Knife',
    category: 'kitchen-accessories',
    price: 14.99,
    stock: 7,
  },
  {
    id: 65,
    title: 'Lunch Box',
    category: 'kitchen-accessories',
    price: 12.99,
    stock: 94,
  },
  {
    id: 66,
    title: 'Microwave Oven',
    category: 'kitchen-accessories',
    price: 89.99,
    stock: 59,
  },
  {
    id: 67,
    title: 'Mug Tree Stand',
    category: 'kitchen-accessories',
    price: 15.99,
    stock: 88,
  },
  {
    id: 68,
    title: 'Pan',
    category: 'kitchen-accessories',
    price: 24.99,
    stock: 90,
  },
  {
    id: 69,
    title: 'Plate',
    category: 'kitchen-accessories',
    price: 3.99,
    stock: 66,
  },
  {
    id: 70,
    title: 'Red Tongs',
    category: 'kitchen-accessories',
    price: 6.99,
    stock: 82,
  },
  {
    id: 71,
    title: 'Silver Pot With Glass Cap',
    category: 'kitchen-accessories',
    price: 39.99,
    stock: 40,
  },
  {
    id: 72,
    title: 'Slotted Turner',
    category: 'kitchen-accessories',
    price: 8.99,
    stock: 88,
  },
  {
    id: 73,
    title: 'Spice Rack',
    category: 'kitchen-accessories',
    price: 19.99,
    stock: 79,
  },
  {
    id: 74,
    title: 'Spoon',
    category: 'kitchen-accessories',
    price: 4.99,
    stock: 59,
  },
  {
    id: 75,
    title: 'Tray',
    category: 'kitchen-accessories',
    price: 16.99,
    stock: 71,
  },
  {
    id: 76,
    title: 'Wooden Rolling Pin',
    category: 'kitchen-accessories',
    price: 11.99,
    stock: 80,
  },
  {
    id: 77,
    title: 'Yellow Peeler',
    category: 'kitchen-accessories',
    price: 5.99,
    stock: 35,
  },
  {
    id: 78,
    title: 'Apple MacBook Pro 14 Inch Space Grey',
    brand: 'Apple',
    category: 'laptops',
    price: 1999.99,
    stock: 24,
  },
  {
    id: 79,
    title: 'Asus Zenbook Pro Dual Screen Laptop',
    brand: 'Asus',
    category: 'laptops',
    price: 1799.99,
    stock: 45,
  },
  {
    id: 80,
    title: 'Huawei Matebook X Pro',
    brand: 'Huawei',
    category: 'laptops',
    price: 1399.99,
    stock: 75,
  },
  {
    id: 81,
    title: 'Lenovo Yoga 920',
    brand: 'Lenovo',
    category: 'laptops',
    price: 1099.99,
    stock: 40,
  },
  {
    id: 82,
    title: 'New DELL XPS 13 9300 Laptop',
    brand: 'Dell',
    category: 'laptops',
    price: 1499.99,
    stock: 74,
  },
  {
    id: 83,
    title: 'Blue & Black Check Shirt',
    brand: 'Fashion Trends',
    category: 'mens-shirts',
    price: 29.99,
    stock: 38,
  },
  {
    id: 84,
    title: 'Gigabyte Aorus Men Tshirt',
    brand: 'Gigabyte',
    category: 'mens-shirts',
    price: 24.99,
    stock: 90,
  },
  {
    id: 85,
    title: 'Man Plaid Shirt',
    brand: 'Classic Wear',
    category: 'mens-shirts',
    price: 34.99,
    stock: 82,
  },
  {
    id: 86,
    title: 'Man Short Sleeve Shirt',
    brand: 'Casual Comfort',
    category: 'mens-shirts',
    price: 19.99,
    stock: 2,
  },
  {
    id: 87,
    title: 'Men Check Shirt',
    brand: 'Urban Chic',
    category: 'mens-shirts',
    price: 27.99,
    stock: 95,
  },
  {
    id: 88,
    title: 'Nike Air Jordan 1 Red And Black',
    brand: 'Nike',
    category: 'mens-shoes',
    price: 149.99,
    stock: 7,
  },
  {
    id: 89,
    title: 'Nike Baseball Cleats',
    brand: 'Nike',
    category: 'mens-shoes',
    price: 79.99,
    stock: 12,
  },
  {
    id: 90,
    title: 'Puma Future Rider Trainers',
    brand: 'Puma',
    category: 'mens-shoes',
    price: 89.99,
    stock: 90,
  },
  {
    id: 91,
    title: 'Sports Sneakers Off White & Red',
    brand: 'Off White',
    category: 'mens-shoes',
    price: 119.99,
    stock: 17,
  },
  {
    id: 92,
    title: 'Sports Sneakers Off White Red',
    brand: 'Off White',
    category: 'mens-shoes',
    price: 109.99,
    stock: 62,
  },
  {
    id: 93,
    title: 'Brown Leather Belt Watch',
    brand: 'Fashion Timepieces',
    category: 'mens-watches',
    price: 89.99,
    stock: 32,
  },
  {
    id: 94,
    title: 'Longines Master Collection',
    brand: 'Longines',
    category: 'mens-watches',
    price: 1499.99,
    stock: 100,
  },
  {
    id: 95,
    title: 'Rolex Cellini Date Black Dial',
    brand: 'Rolex',
    category: 'mens-watches',
    price: 8999.99,
    stock: 40,
  },
  {
    id: 96,
    title: 'Rolex Cellini Moonphase',
    brand: 'Rolex',
    category: 'mens-watches',
    price: 12999.99,
    stock: 36,
  },
  {
    id: 97,
    title: 'Rolex Datejust',
    brand: 'Rolex',
    category: 'mens-watches',
    price: 10999.99,
    stock: 86,
  },
  {
    id: 98,
    title: 'Rolex Submariner Watch',
    brand: 'Rolex',
    category: 'mens-watches',
    price: 13999.99,
    stock: 55,
  },
  {
    id: 99,
    title: 'Amazon Echo Plus',
    brand: 'Amazon',
    category: 'mobile-accessories',
    price: 99.99,
    stock: 61,
  },
  {
    id: 100,
    title: 'Apple Airpods',
    brand: 'Apple',
    category: 'mobile-accessories',
    price: 129.99,
    stock: 67,
  },
  {
    id: 101,
    title: 'Apple AirPods Max Silver',
    brand: 'Apple',
    category: 'mobile-accessories',
    price: 549.99,
    stock: 59,
  },
  {
    id: 102,
    title: 'Apple Airpower Wireless Charger',
    brand: 'Apple',
    category: 'mobile-accessories',
    price: 79.99,
    stock: 1,
  },
  {
    id: 103,
    title: 'Apple HomePod Mini Cosmic Grey',
    brand: 'Apple',
    category: 'mobile-accessories',
    price: 99.99,
    stock: 27,
  },
  {
    id: 104,
    title: 'Apple iPhone Charger',
    brand: 'Apple',
    category: 'mobile-accessories',
    price: 19.99,
    stock: 31,
  },
  {
    id: 105,
    title: 'Apple MagSafe Battery Pack',
    brand: 'Apple',
    category: 'mobile-accessories',
    price: 99.99,
    stock: 1,
  },
  {
    id: 106,
    title: 'Apple Watch Series 4 Gold',
    brand: 'Apple',
    category: 'mobile-accessories',
    price: 349.99,
    stock: 33,
  },
  {
    id: 107,
    title: 'Beats Flex Wireless Earphones',
    brand: 'Beats',
    category: 'mobile-accessories',
    price: 49.99,
    stock: 50,
  },
  {
    id: 108,
    title: 'iPhone 12 Silicone Case with MagSafe Plum',
    brand: 'Apple',
    category: 'mobile-accessories',
    price: 29.99,
    stock: 69,
  },
  {
    id: 109,
    title: 'Monopod',
    brand: 'TechGear',
    category: 'mobile-accessories',
    price: 19.99,
    stock: 48,
  },
  {
    id: 110,
    title: 'Selfie Lamp with iPhone',
    brand: 'GadgetMaster',
    category: 'mobile-accessories',
    price: 14.99,
    stock: 58,
  },
  {
    id: 111,
    title: 'Selfie Stick Monopod',
    brand: 'SnapTech',
    category: 'mobile-accessories',
    price: 12.99,
    stock: 11,
  },
  {
    id: 112,
    title: 'TV Studio Camera Pedestal',
    brand: 'ProVision',
    category: 'mobile-accessories',
    price: 499.99,
    stock: 15,
  },
  {
    id: 113,
    title: 'Generic Motorcycle',
    brand: 'Generic Motors',
    category: 'motorcycle',
    price: 3999.99,
    stock: 34,
  },
  {
    id: 114,
    title: 'Kawasaki Z800',
    brand: 'Kawasaki',
    category: 'motorcycle',
    price: 8999.99,
    stock: 52,
  },
  {
    id: 115,
    title: 'MotoGP CI.H1',
    brand: 'MotoGP',
    category: 'motorcycle',
    price: 14999.99,
    stock: 10,
  },
  {
    id: 116,
    title: 'Scooter Motorcycle',
    brand: 'ScootMaster',
    category: 'motorcycle',
    price: 2999.99,
    stock: 84,
  },
  {
    id: 117,
    title: 'Sportbike Motorcycle',
    brand: 'SpeedMaster',
    category: 'motorcycle',
    price: 7499.99,
    stock: 0,
  },
  {
    id: 118,
    title: 'Attitude Super Leaves Hand Soap',
    brand: 'Attitude',
    category: 'skin-care',
    price: 8.99,
    stock: 94,
  },
  {
    id: 119,
    title: 'Olay Ultra Moisture Shea Butter Body Wash',
    brand: 'Olay',
    category: 'skin-care',
    price: 12.99,
    stock: 34,
  },
  {
    id: 120,
    title: 'Vaseline Men Body and Face Lotion',
    brand: 'Vaseline',
    category: 'skin-care',
    price: 9.99,
    stock: 95,
  },
  {
    id: 121,
    title: 'iPhone 5s',
    brand: 'Apple',
    category: 'smartphones',
    price: 199.99,
    stock: 25,
  },
  {
    id: 122,
    title: 'iPhone 6',
    brand: 'Apple',
    category: 'smartphones',
    price: 299.99,
    stock: 60,
  },
  {
    id: 123,
    title: 'iPhone 13 Pro',
    brand: 'Apple',
    category: 'smartphones',
    price: 1099.99,
    stock: 56,
  },
  {
    id: 124,
    title: 'iPhone X',
    brand: 'Apple',
    category: 'smartphones',
    price: 899.99,
    stock: 37,
  },
  {
    id: 125,
    title: 'Oppo A57',
    brand: 'Oppo',
    category: 'smartphones',
    price: 249.99,
    stock: 19,
  },
  {
    id: 126,
    title: 'Oppo F19 Pro Plus',
    brand: 'Oppo',
    category: 'smartphones',
    price: 399.99,
    stock: 78,
  },
  {
    id: 127,
    title: 'Oppo K1',
    brand: 'Oppo',
    category: 'smartphones',
    price: 299.99,
    stock: 55,
  },
  {
    id: 128,
    title: 'Realme C35',
    brand: 'Realme',
    category: 'smartphones',
    price: 149.99,
    stock: 48,
  },
  {
    id: 129,
    title: 'Realme X',
    brand: 'Realme',
    category: 'smartphones',
    price: 299.99,
    stock: 12,
  },
  {
    id: 130,
    title: 'Realme XT',
    brand: 'Realme',
    category: 'smartphones',
    price: 349.99,
    stock: 80,
  },
  {
    id: 131,
    title: 'Samsung Galaxy S7',
    brand: 'Samsung',
    category: 'smartphones',
    price: 299.99,
    stock: 67,
  },
  {
    id: 132,
    title: 'Samsung Galaxy S8',
    brand: 'Samsung',
    category: 'smartphones',
    price: 499.99,
    stock: 0,
  },
  {
    id: 133,
    title: 'Samsung Galaxy S10',
    brand: 'Samsung',
    category: 'smartphones',
    price: 699.99,
    stock: 19,
  },
  {
    id: 134,
    title: 'Vivo S1',
    brand: 'Vivo',
    category: 'smartphones',
    price: 249.99,
    stock: 50,
  },
  {
    id: 135,
    title: 'Vivo V9',
    brand: 'Vivo',
    category: 'smartphones',
    price: 299.99,
    stock: 82,
  },
  {
    id: 136,
    title: 'Vivo X21',
    brand: 'Vivo',
    category: 'smartphones',
    price: 499.99,
    stock: 7,
  },
  {
    id: 137,
    title: 'American Football',
    category: 'sports-accessories',
    price: 19.99,
    stock: 53,
  },
  {
    id: 138,
    title: 'Baseball Ball',
    category: 'sports-accessories',
    price: 8.99,
    stock: 100,
  },
  {
    id: 139,
    title: 'Baseball Glove',
    category: 'sports-accessories',
    price: 24.99,
    stock: 22,
  },
  {
    id: 140,
    title: 'Basketball',
    category: 'sports-accessories',
    price: 14.99,
    stock: 75,
  },
  {
    id: 141,
    title: 'Basketball Rim',
    category: 'sports-accessories',
    price: 39.99,
    stock: 43,
  },
  {
    id: 142,
    title: 'Cricket Ball',
    category: 'sports-accessories',
    price: 12.99,
    stock: 30,
  },
  {
    id: 143,
    title: 'Cricket Bat',
    category: 'sports-accessories',
    price: 29.99,
    stock: 98,
  },
  {
    id: 144,
    title: 'Cricket Helmet',
    category: 'sports-accessories',
    price: 44.99,
    stock: 10,
  },
  {
    id: 145,
    title: 'Cricket Wicket',
    category: 'sports-accessories',
    price: 29.99,
    stock: 25,
  },
  {
    id: 146,
    title: 'Feather Shuttlecock',
    category: 'sports-accessories',
    price: 5.99,
    stock: 95,
  },
  {
    id: 147,
    title: 'Football',
    category: 'sports-accessories',
    price: 17.99,
    stock: 96,
  },
  {
    id: 148,
    title: 'Golf Ball',
    category: 'sports-accessories',
    price: 9.99,
    stock: 84,
  },
  {
    id: 149,
    title: 'Iron Golf',
    category: 'sports-accessories',
    price: 49.99,
    stock: 90,
  },
  {
    id: 150,
    title: 'Metal Baseball Bat',
    category: 'sports-accessories',
    price: 29.99,
    stock: 16,
  },
  {
    id: 151,
    title: 'Tennis Ball',
    category: 'sports-accessories',
    price: 6.99,
    stock: 28,
  },
  {
    id: 152,
    title: 'Tennis Racket',
    category: 'sports-accessories',
    price: 49.99,
    stock: 6,
  },
  {
    id: 153,
    title: 'Volleyball',
    category: 'sports-accessories',
    price: 11.99,
    stock: 0,
  },
  {
    id: 154,
    title: 'Black Sun Glasses',
    brand: 'Fashion Shades',
    category: 'sunglasses',
    price: 29.99,
    stock: 60,
  },
  {
    id: 155,
    title: 'Classic Sun Glasses',
    brand: 'Fashion Shades',
    category: 'sunglasses',
    price: 24.99,
    stock: 1,
  },
  {
    id: 156,
    title: 'Green and Black Glasses',
    brand: 'Fashion Shades',
    category: 'sunglasses',
    price: 34.99,
    stock: 24,
  },
  {
    id: 157,
    title: 'Party Glasses',
    brand: 'Fashion Fun',
    category: 'sunglasses',
    price: 19.99,
    stock: 86,
  },
  {
    id: 158,
    title: 'Sunglasses',
    brand: 'Fashion Shades',
    category: 'sunglasses',
    price: 22.99,
    stock: 27,
  },
  {
    id: 159,
    title: 'iPad Mini 2021 Starlight',
    brand: 'Apple',
    category: 'tablets',
    price: 499.99,
    stock: 47,
  },
  {
    id: 160,
    title: 'Samsung Galaxy Tab S8 Plus Grey',
    brand: 'Samsung',
    category: 'tablets',
    price: 599.99,
    stock: 62,
  },
  {
    id: 161,
    title: 'Samsung Galaxy Tab White',
    brand: 'Samsung',
    category: 'tablets',
    price: 349.99,
    stock: 92,
  },
  {
    id: 162,
    title: 'Blue Frock',
    category: 'tops',
    price: 29.99,
    stock: 52,
  },
  {
    id: 163,
    title: 'Girl Summer Dress',
    category: 'tops',
    price: 19.99,
    stock: 43,
  },
  {
    id: 164,
    title: 'Gray Dress',
    category: 'tops',
    price: 34.99,
    stock: 55,
  },
  {
    id: 165,
    title: 'Short Frock',
    category: 'tops',
    price: 24.99,
    stock: 22,
  },
  {
    id: 166,
    title: 'Tartan Dress',
    category: 'tops',
    price: 39.99,
    stock: 73,
  },
  {
    id: 167,
    title: '300 Touring',
    brand: 'Chrysler',
    category: 'vehicle',
    price: 28999.99,
    stock: 54,
  },
  {
    id: 168,
    title: 'Charger SXT RWD',
    brand: 'Dodge',
    category: 'vehicle',
    price: 32999.99,
    stock: 57,
  },
  {
    id: 169,
    title: 'Dodge Hornet GT Plus',
    brand: 'Dodge',
    category: 'vehicle',
    price: 24999.99,
    stock: 82,
  },
  {
    id: 170,
    title: 'Durango SXT RWD',
    brand: 'Dodge',
    category: 'vehicle',
    price: 36999.99,
    stock: 95,
  },
  {
    id: 171,
    title: 'Pacifica Touring',
    brand: 'Chrysler',
    category: 'vehicle',
    price: 31999.99,
    stock: 53,
  },
  {
    id: 172,
    title: "Blue Women's Handbag",
    brand: 'Fashionista',
    category: 'womens-bags',
    price: 49.99,
    stock: 76,
  },
  {
    id: 173,
    title: "Heshe Women's Leather Bag",
    brand: 'Heshe',
    category: 'womens-bags',
    price: 129.99,
    stock: 99,
  },
  {
    id: 174,
    title: 'Prada Women Bag',
    brand: 'Prada',
    category: 'womens-bags',
    price: 599.99,
    stock: 75,
  },
  {
    id: 175,
    title: 'White Faux Leather Backpack',
    brand: 'Urban Chic',
    category: 'womens-bags',
    price: 39.99,
    stock: 39,
  },
  {
    id: 176,
    title: 'Women Handbag Black',
    brand: 'Elegance Collection',
    category: 'womens-bags',
    price: 59.99,
    stock: 11,
  },
  {
    id: 177,
    title: "Black Women's Gown",
    category: 'womens-dresses',
    price: 129.99,
    stock: 25,
  },
  {
    id: 178,
    title: 'Corset Leather With Skirt',
    category: 'womens-dresses',
    price: 89.99,
    stock: 30,
  },
  {
    id: 179,
    title: 'Corset With Black Skirt',
    category: 'womens-dresses',
    price: 79.99,
    stock: 33,
  },
  {
    id: 180,
    title: 'Dress Pea',
    category: 'womens-dresses',
    price: 49.99,
    stock: 6,
  },
  {
    id: 181,
    title: 'Marni Red & Black Suit',
    category: 'womens-dresses',
    price: 179.99,
    stock: 62,
  },
  {
    id: 182,
    title: 'Green Crystal Earring',
    category: 'womens-jewellery',
    price: 29.99,
    stock: 54,
  },
  {
    id: 183,
    title: 'Green Oval Earring',
    category: 'womens-jewellery',
    price: 24.99,
    stock: 73,
  },
  {
    id: 184,
    title: 'Tropical Earring',
    category: 'womens-jewellery',
    price: 19.99,
    stock: 1,
  },
  {
    id: 185,
    title: 'Black & Brown Slipper',
    brand: 'Comfort Trends',
    category: 'womens-shoes',
    price: 19.99,
    stock: 3,
  },
  {
    id: 186,
    title: 'Calvin Klein Heel Shoes',
    brand: 'Calvin Klein',
    category: 'womens-shoes',
    price: 79.99,
    stock: 93,
  },
  {
    id: 187,
    title: 'Golden Shoes Woman',
    brand: 'Fashion Diva',
    category: 'womens-shoes',
    price: 49.99,
    stock: 88,
  },
  {
    id: 188,
    title: 'Pampi Shoes',
    brand: 'Pampi',
    category: 'womens-shoes',
    price: 29.99,
    stock: 49,
  },
  {
    id: 189,
    title: 'Red Shoes',
    brand: 'Fashion Express',
    category: 'womens-shoes',
    price: 34.99,
    stock: 7,
  },
  {
    id: 190,
    title: 'IWC Ingenieur Automatic Steel',
    brand: 'IWC',
    category: 'womens-watches',
    price: 4999.99,
    stock: 90,
  },
  {
    id: 191,
    title: 'Rolex Cellini Moonphase',
    brand: 'Rolex',
    category: 'womens-watches',
    price: 15999.99,
    stock: 52,
  },
  {
    id: 192,
    title: 'Rolex Datejust Women',
    brand: 'Rolex',
    category: 'womens-watches',
    price: 10999.99,
    stock: 4,
  },
  {
    id: 193,
    title: 'Watch Gold for Women',
    brand: 'Fashion Gold',
    category: 'womens-watches',
    price: 799.99,
    stock: 0,
  },
  {
    id: 194,
    title: "Women's Wrist Watch",
    brand: 'Fashion Co.',
    category: 'womens-watches',
    price: 129.99,
    stock: 12,
  },
];
